# Generated by Django 4.2.14 on 2024-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descrption',
            field=models.TextField(),
        ),
    ]
